### ISSUE TITLE
Bad dir creation

### ISSUE THREAD

**Issue by refrain** [33hops/xsibackup#1]
Running on ESXi 5.5.

command arguments: ./xsibackup --backup-point=/
vmfs/volumes/backups/vrr --backup-type=custom --backup-vms="Vxxxx Report Remit"

In line 980, the $2 variable contains the vmx filename and has a quotation mark and a comma at the end of the string: ",

which creates this directory...

/vmfs/volumes/backups/vrr/20150330112457/vxxxx-phase1.vmx",

I get the following errors from the script:

cp: can't stat '/*.vmx': No such file or directory
grep: /*.vmx: No such file or directory

Traced back to getVMDir() function... must be some error in that string processing.

**Comment by 33hops** [comment]
That variable there stores the backup root for the current VM. I don't know where that comma is coming out from, but XSIBackup is not generating it.
