### ISSUE TITLE
Empty Backup report

### ISSUE THREAD

**Issue by NoLooseEnds** [33hops/xsibackup#3]
Just installed and tested a backup now. The backup report I get is empty. I first used test-mode, and then a normal backup, both produced same empty mail.

```
# /vmfs/volumes/OS2/bin/xsibackup --backup-point=/vmfs/volumes/OS2/Backup --backup-type=custom --backup-vms="<NAME> (Ubuntu Serve
r)" -mail-from=<from@mail.com> --mail-to=<to@mail.com> --smtp-srv=mail.server.com --smtp-port=25 --smtp-usr=username --smtp-pwd=password
Thu, 09 Apr 2015 13:49:13 +0000
Found --backup-point at /vmfs/volumes/OS2/Backup
Getting list of all VMs...
10     <NAME> (OmniOS)           [OS1] napp-it-14b/napp-it-14b.vmx                   solaris10_64Guest   vmx-08
7      <NAME> (Mac OS X)        [OS1] OSX/OSX.vmx                                   darwin11_64Guest    vmx-10
8      <NAME> (Ubuntu Server)   [OS1] Ubuntu Server 14.04/Ubuntu Server 14.04.vmx   ubuntu64Guest       vmx-08
VMs to backup:
8      <NAME> (Ubuntu Server)   [OS1] Ubuntu Server 14.04/Ubuntu Server 14.04.vmx   ubuntu64Guest       vmx-08
Needed room: 40 Gb.
Available room: 342 Gb.
Hot backup selected for VM: <NAME> (Ubuntu Server) will not be switched off
All snapshots removed for <NAME> (Ubuntu Server)
Destination disk format: VMFS thin-provisioned
Cloning disk '/vmfs/volumes/51cf0238-c3bd2d98-deca-6805ca1897e3/Ubuntu Server 14.04/Ubuntu Server 14.04.vmdk'...
Clone: 100% done.
Opening port 25 for SMTPout service...
220 osl1cloudm2 cmsmtp ESMTP server ready
250 osl1cloudm2 hello [XX.XX.XX.XX], pleased to meet you
250-osl1cloudm2 hello [XX.XX.XX.XX], pleased to meet you
250-HELP
250-AUTH LOGIN PLAIN
250-SIZE 209715200
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-STARTTLS
250 OK
334 VXNlcm5hbWU6
334 UGFzc3dvcmQ6
235 2.7.0 ... authentication succeeded
250 2.1.0 <from@mail.com> sender ok
250 2.1.5 <to@mail.com> recipient ok
354 OK
250 2.0.0 gD0hYoH9boc4PgD0iYLqpF mail accepted for delivery
Firewall rule SMTPout closed.
```

Mail Screenshot:
![mail screenshot](https://i.imgur.com/cFGEsPK.png)

Thanks.

**Comment by 33hops** [comment]
This is the first news I have about this kind of failure. Have you checked that that the HTML is not there?. It looks like an HTML missinterpretation from part of the e-mail client and by taking a glance at your screen capture it seems like this issue could be caused by the Twitter widget.

Which mail client are you using?
Please try to read the message from a different mail client. We have tested various clients like Outlook, Android, OSX, and different webmail: Roundcube, Hotmail, Gmail and they work O.K.

The main support site is at: http://sourceforge.net/p/xsibackup/discussion/?source=navbar
Please send support requests there

**Comment by NoLooseEnds** [comment]
Thanks. 

It seems that I am not able to post at the Sourceforge forum? Even though I am logged in.

Anyways. I have viewed the mail in three mailclients. Mailplane (essential Google Mail web), Mailbox and  Google Mail. It is sending to an Google Apps account. I can't see any of the missing mail if I go and read the HTML code, so it appears it just not there.

**Comment by 33hops** [comment]
I don't know what to tell you either with your problems at sourceforge.net or with the mails. Reinstall XSIBackup following the recommended procedure and avoid doing things out of the recommendations found at the README file. I attach two screen captures of e-mail tests sent to Roundcube and GMail
![gmail](https://cloud.githubusercontent.com/assets/3033761/7157235/468708e2-e36e-11e4-8c66-06471034a929.png)
![roundcube](https://cloud.githubusercontent.com/assets/3033761/7157236/4696f82e-e36e-11e4-9a44-6d93c4a7de9d.png)

**Comment by NoLooseEnds** [comment]
I took another go on this issue. I first tried to edit the html code and see if that was causing the error, but no go.

I then changed to another SMTP server, and everything started working. I don't know what the issue was, but the issue is with the SMTP server.

**Comment by 33hops** [comment]
Well, we have designed XSIBackup to comply with SMTP RFC. 
https://www.ietf.org/rfc/rfc2821.txt

We cannot guaratee it will work with every mail server.
