### ISSUE TITLE
Issue with email in vSphere 6.0.0

### ISSUE THREAD

**Issue by shockwavecs** [33hops/xsibackup#5]
It appears the email function is not working. SMTPout is no longer a ruleset to modify.

[root@hqvmware1:~] /vmfs/volumes/hqvmware1LocalHDD/xsibackup/xsibackup --test-mode=true --mail-from=root@hqvmware1 --subject="HQVMWARE1 XSI Backup Repo
rt" --mail-to=jedmands@mydomain.com --smtp-srv=<myrelay> --smtp-usr=j.edmands@<mydomain> --smtp-pwd=<my password> --backup-point="/vmfs/volumes/hqbacula1 RAID 6 VM XSI Backup HQVC2" --backup-type=custom --backup-vms=devqa1
Mon, 04 May 2015 18:56:57 +0000
sh: RAID: unknown operand
Found --backup-point at /vmfs/volumes/hqbacula1 RAID 6 VM XSI Backup HQVC2
Getting list of all VMs...
...
...
(Removed for sanity sake)
...
...
Needed room: 32 Gb.
Available room: 4018 Gb.
Hot backup selected for VM: devqa1 will not be switched off
Test mode activated VMs will not be cloned, please remove --test-mode=true to allow backups
Int value is not found Firewall rule SMTPout added...
usage: nc [-46DdhklnrStUuvzC] [-i interval] [-p source_port]
	  [-s source_ip_address] [-T ToS] [-w timeout] [-X proxy_version]
	  [-x proxy_address[:port]] [hostname] [port[s]]

[root@hqvmware1:~] esxcli network firewall ruleset set 
[root@hqvmware1:~] esxcli network firewall ruleset set --ruleset-id=SMTPout --enabled=true
Invalid Ruleset Id.

**Comment by 33hops** [comment]
We have it working here on ESXi 6.0.0 without any problem. 
I can't be sure from the info you are giving but do make sure that you are providing the port number according to the manual and the examples. Please use Sourceforge's discussion group for a more rapid response https://sourceforge.net/p/xsibackup/discussion/?source=navbar

**Comment by shockwavecs** [comment]
woops. It does work. Sorry. Thanks for the update.
