### ISSUE TITLE
rsync option doesn't work for VM with space in name

### ISSUE THREAD

**Issue by jpiel** [33hops/xsibackup#7]
xsibackup: 4.3.0
ESXi: 5.5u2

In all my VMs, i have a few with space in game (i know it is bad, i will probably work on that, but the bug right under remains).

When using xsibackup to backup to another local datastore using the standard option it works well. But when i'm using it with the rsync option as --backup-prog, then it fails.

The error i get in email is "ERRORS FOUND:
Wed May 27 14:03:49 UTC 2015 - Exit code: 33 - Error message: Missing file, cannot copy: /vmfs/volumes/54edd4a7-694cb23c-ee69-001e52f3e01c/Windows XP Pro//Windows"

**Comment by 33hops** [comment]
We'll fix that in 4.3.1, try to avoid spaces whenever possible
